"""
@Description :   an example
@Author      :   lixiaoming
@Date        :   2024/12/17
@Contact     :   lixiaoming233@icloud.com
"""
import os
from utils import get_xml_similarity
from adapter import json2xml

if __name__ == "__main__":

    # Method for calculating similarity for `state_.json` files generated by Droidbot
    json_file_1 = "path/to/json/file1"
    json_file_2 = "path/to/json/file2"

    res_1 = get_xml_similarity(json2xml(json_file_1), json2xml(json_file_2), tol=0.1)
    print(res_1)

    # Method for Calculating similarity for xml files exported by `adb uiautomator`
    xml_file_1 = "path/to/xml/file1"
    xml_file_2 = "path/to/xml/file2"
    with open(xml_file_1, 'r', encoding='utf-8') as file:
        xml_doc_1 = file.read()
    with open(xml_file_2, 'r', encoding='utf-8') as file:
        xml_doc_2 = file.read()

    res_2 = get_xml_similarity(xml_doc_1, xml_doc_2, tol=0.1)
    print(res_2)

    # Method for calculating similarity for html files of web pages
    html_file_1 = "path/to/html/file1"
    html_file_2 = "path/to/html/file2"
    with open(html_file_1, 'r', encoding='utf-8') as file:
        html_doc_1 = file.read()
    with open(html_file_2, 'r', encoding='utf-8') as file:
        html_doc_2 = file.read()
    res_3 = get_xml_similarity(html_doc_1, html_doc_2, tol=0.1, features="lxml")
    print(res_3)
